### ISSUE TITLE
Add docs to `sev`

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#347] opened 2020-03-18 20:11 UTC
The `sev` crate currently fails the `#![deny(missing_docs)]` lint test. It's been grandfathered in to make the tests pass, but we should add docs to make the test pass properly.

**Comment by connorkuehl** [comment] 2020-09-01 22:21
Duplicate of https://github.com/enarx/sev/issues/2

This issue is older but the other issue is tracked in the repo where the code is, so I will close this one in favor of that one.

**Closed by connorkuehl** 2020-09-01 22:21 UTC
Labels: amd sev, debt
