### ISSUE TITLE
Place Project Technical Charter in repo (top-level)

### ISSUE THREAD

**Issue by MikeCamel** [enarx/enarx#816] opened 2020-08-12 10:52 UTC
**Description**

Linux Foundation/CCC rules are that our Technical Charter should be available at the top level of the repo.  File attached.

First we need to decide if we need to change it, then post when done.

[Enarx_Project_Technical_Charter_2-14-2020.pdf](https://github.com/enarx/enarx/files/5062187/Enarx_Project_Technical_Charter_2-14-2020.pdf)

**Comment by axelsimon** [comment] 2020-09-30 14:16
I'm going to close this one, as it is really boils down to being a duplicate of #805.

**Closed by axelsimon** 2020-09-30 14:16 UTC
Labels: documentation
