### ISSUE TITLE
[Infrastructure]: Automate rust-toolchain update chore

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1465] opened 2022-02-28 20:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Provide scripts for updating rust toolchain to be used for future automation.

**Comment by rvolosatovs** [comment] 2022-03-14 08:58
Duplicate of https://github.com/enarx/enarx/issues/1363?

**Closed** 2022-04-11 19:48 UTC
Labels: infrastructure, triage
