### ISSUE TITLE
Run SEV payload during cargo make test

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#553] opened 2020-05-21 21:54 UTC
We can currently run `cargo make test` to run our tests. When we run these on an SEV enabled system, we also want to run an integration test that executes the payload binary in an SEV Keep.

This is a mirror issue to #522 for SGX.

**Comment by connorkuehl** [comment] 2020-07-20 16:38
I accidentally made a duplicate of this issue.

Here's some extra info for posterity since I typed it up and don't want it to be for nothing :sweat_smile: 

The `has_sev` compiler attribute must be enabled in [integration-tests/build.rs](https://github.com/enarx/enarx/blob/master/integration-tests/build.rs).

Depends on:
- [ ] Shim support for running payload (currently included in PR #684)

**Comment by haraldh** [comment] 2020-09-10 14:42
Depends on:
https://github.com/enarx/enarx-keepldr/pull/12
https://github.com/enarx/enarx-keepldr/pull/11
and
https://github.com/enarx/enarx/issues/905

**Comment by connorkuehl** [comment] 2020-09-23 13:19
All pre-requisites have been merged. SEV integration tests are incorporated with the CI.

**Closed by connorkuehl** 2020-09-23 13:19 UTC
Labels: amd sev, debt, enhancement
