### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#36] opened 2019-12-11 21:56 UTC
We need one.

**Comment by axelsimon** [comment] 2019-12-16 12:13
Duplicate of enarx/enarx.github.io#13, closing. Let's track this in that original issue.

**Comment by MikeCamel** [comment] 2020-01-06 13:30
This is suggested from the Confidential Computing Consortium: https://github.com/confidential-computing/governance/pull/1/commits/0bd4f13a6846a37fc36f363de89a2642cd845c62

**Comment by axelsimon** [comment] 2020-03-16 16:49
I've moved the original issue to enarx/enarx, it is now issue #335.
Closing this one, the other one contains more history.

**Closed by axelsimon** 2020-03-16 16:49 UTC
Labels: infrastructure
