### ISSUE TITLE
Load and run a Linux ELF binary inside a VM that calls SYS_exit

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#72] opened 2020-01-03 22:43 UTC
This is done when we can load and run a toy static Linux ELF binary inside a VM that does nothing more than call `SYS_exit` with the code in the `enarx/enarx` repo.

**Comment by connorkuehl** [comment] 2020-03-12 17:33
(Now) duplicate of #309

**Comment by connorkuehl** [comment] 2020-03-12 17:34
Actually, this issue's main comment does capture an item on our SEV roadmap.

**Closed** 2020-08-07 14:19 UTC
Labels: amd sev
